// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proxy.proto

package pb

import (
    context "context"
    fmt "fmt"
    proto "github.com/golang/protobuf/proto"
    grpc "google.golang.org/grpc"
    codes "google.golang.org/grpc/codes"
    status "google.golang.org/grpc/status"
    math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// ProxyReplyOnly 应答消息
type ProxyReplyOnly struct {
    Code                 string   `protobuf:"bytes,1,opt,name=Code,proto3" json:"Code,omitempty"`
    Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
    XXX_NoUnkeyedLiteral struct{} `json:"-"`
    XXX_unrecognized     []byte   `json:"-"`
    XXX_sizecache        int32    `json:"-"`
}

func (m *ProxyReplyOnly) Reset()         { *m = ProxyReplyOnly{} }
func (m *ProxyReplyOnly) String() string { return proto.CompactTextString(m) }
func (*ProxyReplyOnly) ProtoMessage()    {}
func (*ProxyReplyOnly) Descriptor() ([]byte, []int) {
    return fileDescriptor_700b50b08ed8dbaf, []int{0}
}

func (m *ProxyReplyOnly) XXX_Unmarshal(b []byte) error {
    return xxx_messageInfo_ProxyReplyOnly.Unmarshal(m, b)
}
func (m *ProxyReplyOnly) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
    return xxx_messageInfo_ProxyReplyOnly.Marshal(b, m, deterministic)
}
func (m *ProxyReplyOnly) XXX_Merge(src proto.Message) {
    xxx_messageInfo_ProxyReplyOnly.Merge(m, src)
}
func (m *ProxyReplyOnly) XXX_Size() int {
    return xxx_messageInfo_ProxyReplyOnly.Size(m)
}
func (m *ProxyReplyOnly) XXX_DiscardUnknown() {
    xxx_messageInfo_ProxyReplyOnly.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyReplyOnly proto.InternalMessageInfo

func (m *ProxyReplyOnly) GetCode() string {
    if m != nil {
        return m.Code
    }
    return ""
}

func (m *ProxyReplyOnly) GetMessage() string {
    if m != nil {
        return m.Message
    }
    return ""
}

type ProxyStopRequest struct {
    XXX_NoUnkeyedLiteral struct{} `json:"-"`
    XXX_unrecognized     []byte   `json:"-"`
    XXX_sizecache        int32    `json:"-"`
}

func (m *ProxyStopRequest) Reset()         { *m = ProxyStopRequest{} }
func (m *ProxyStopRequest) String() string { return proto.CompactTextString(m) }
func (*ProxyStopRequest) ProtoMessage()    {}
func (*ProxyStopRequest) Descriptor() ([]byte, []int) {
    return fileDescriptor_700b50b08ed8dbaf, []int{1}
}

func (m *ProxyStopRequest) XXX_Unmarshal(b []byte) error {
    return xxx_messageInfo_ProxyStopRequest.Unmarshal(m, b)
}
func (m *ProxyStopRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
    return xxx_messageInfo_ProxyStopRequest.Marshal(b, m, deterministic)
}
func (m *ProxyStopRequest) XXX_Merge(src proto.Message) {
    xxx_messageInfo_ProxyStopRequest.Merge(m, src)
}
func (m *ProxyStopRequest) XXX_Size() int {
    return xxx_messageInfo_ProxyStopRequest.Size(m)
}
func (m *ProxyStopRequest) XXX_DiscardUnknown() {
    xxx_messageInfo_ProxyStopRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyStopRequest proto.InternalMessageInfo

type ProxyHealthzRequest struct {
    XXX_NoUnkeyedLiteral struct{} `json:"-"`
    XXX_unrecognized     []byte   `json:"-"`
    XXX_sizecache        int32    `json:"-"`
}

func (m *ProxyHealthzRequest) Reset()         { *m = ProxyHealthzRequest{} }
func (m *ProxyHealthzRequest) String() string { return proto.CompactTextString(m) }
func (*ProxyHealthzRequest) ProtoMessage()    {}
func (*ProxyHealthzRequest) Descriptor() ([]byte, []int) {
    return fileDescriptor_700b50b08ed8dbaf, []int{2}
}

func (m *ProxyHealthzRequest) XXX_Unmarshal(b []byte) error {
    return xxx_messageInfo_ProxyHealthzRequest.Unmarshal(m, b)
}
func (m *ProxyHealthzRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
    return xxx_messageInfo_ProxyHealthzRequest.Marshal(b, m, deterministic)
}
func (m *ProxyHealthzRequest) XXX_Merge(src proto.Message) {
    xxx_messageInfo_ProxyHealthzRequest.Merge(m, src)
}
func (m *ProxyHealthzRequest) XXX_Size() int {
    return xxx_messageInfo_ProxyHealthzRequest.Size(m)
}
func (m *ProxyHealthzRequest) XXX_DiscardUnknown() {
    xxx_messageInfo_ProxyHealthzRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyHealthzRequest proto.InternalMessageInfo

// ProxyDisconnectRequest 断开连接请求
type ProxyDisconnectRequest struct {
    Protocol             string   `protobuf:"bytes,1,opt,name=Protocol,proto3" json:"Protocol,omitempty"`
    InConnIP             string   `protobuf:"bytes,2,opt,name=InConnIP,proto3" json:"InConnIP,omitempty"`
    OutConnIP            string   `protobuf:"bytes,3,opt,name=OutConnIP,proto3" json:"OutConnIP,omitempty"`
    InConnPort           uint32   `protobuf:"varint,4,opt,name=InConnPort,proto3" json:"InConnPort,omitempty"`
    OutConnPort          uint32   `protobuf:"varint,5,opt,name=OutConnPort,proto3" json:"OutConnPort,omitempty"`
    XXX_NoUnkeyedLiteral struct{} `json:"-"`
    XXX_unrecognized     []byte   `json:"-"`
    XXX_sizecache        int32    `json:"-"`
}

func (m *ProxyDisconnectRequest) Reset()         { *m = ProxyDisconnectRequest{} }
func (m *ProxyDisconnectRequest) String() string { return proto.CompactTextString(m) }
func (*ProxyDisconnectRequest) ProtoMessage()    {}
func (*ProxyDisconnectRequest) Descriptor() ([]byte, []int) {
    return fileDescriptor_700b50b08ed8dbaf, []int{3}
}

func (m *ProxyDisconnectRequest) XXX_Unmarshal(b []byte) error {
    return xxx_messageInfo_ProxyDisconnectRequest.Unmarshal(m, b)
}
func (m *ProxyDisconnectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
    return xxx_messageInfo_ProxyDisconnectRequest.Marshal(b, m, deterministic)
}
func (m *ProxyDisconnectRequest) XXX_Merge(src proto.Message) {
    xxx_messageInfo_ProxyDisconnectRequest.Merge(m, src)
}
func (m *ProxyDisconnectRequest) XXX_Size() int {
    return xxx_messageInfo_ProxyDisconnectRequest.Size(m)
}
func (m *ProxyDisconnectRequest) XXX_DiscardUnknown() {
    xxx_messageInfo_ProxyDisconnectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyDisconnectRequest proto.InternalMessageInfo

func (m *ProxyDisconnectRequest) GetProtocol() string {
    if m != nil {
        return m.Protocol
    }
    return ""
}

func (m *ProxyDisconnectRequest) GetInConnIP() string {
    if m != nil {
        return m.InConnIP
    }
    return ""
}

func (m *ProxyDisconnectRequest) GetOutConnIP() string {
    if m != nil {
        return m.OutConnIP
    }
    return ""
}

func (m *ProxyDisconnectRequest) GetInConnPort() uint32 {
    if m != nil {
        return m.InConnPort
    }
    return 0
}

func (m *ProxyDisconnectRequest) GetOutConnPort() uint32 {
    if m != nil {
        return m.OutConnPort
    }
    return 0
}

func init() {
    proto.RegisterType((*ProxyReplyOnly)(nil), "pb.ProxyReplyOnly")
    proto.RegisterType((*ProxyStopRequest)(nil), "pb.ProxyStopRequest")
    proto.RegisterType((*ProxyHealthzRequest)(nil), "pb.ProxyHealthzRequest")
    proto.RegisterType((*ProxyDisconnectRequest)(nil), "pb.ProxyDisconnectRequest")
}

func init() {
    proto.RegisterFile("proxy.proto", fileDescriptor_700b50b08ed8dbaf)
}

var fileDescriptor_700b50b08ed8dbaf = []byte{
    // 269 bytes of a gzipped FileDescriptorProto
    0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xcf, 0x4a, 0xc3, 0x40,
    0x10, 0xc6, 0xd9, 0x9a, 0x5a, 0x3b, 0x45, 0x91, 0xf1, 0x5f, 0x08, 0x22, 0x21, 0xa7, 0x9e, 0x82,
    0x28, 0x78, 0x12, 0x2f, 0xf5, 0x60, 0x0f, 0xd2, 0x10, 0x9f, 0xa0, 0x89, 0x8b, 0x0a, 0x61, 0x67,
    0x4d, 0xb6, 0x60, 0x7c, 0x29, 0x7d, 0x44, 0xd9, 0x71, 0xbb, 0xa9, 0x36, 0xb7, 0x9d, 0xdf, 0xf7,
    0x0d, 0x33, 0xdf, 0x2c, 0x4c, 0x74, 0x4d, 0x1f, 0x6d, 0xaa, 0x6b, 0x32, 0x84, 0x03, 0x5d, 0x24,
    0x77, 0x70, 0x90, 0x59, 0x94, 0x4b, 0x5d, 0xb5, 0x0b, 0x55, 0xb5, 0x88, 0x10, 0xcc, 0xe8, 0x59,
    0x86, 0x22, 0x16, 0xd3, 0x71, 0xce, 0x6f, 0x0c, 0x61, 0xf4, 0x28, 0x9b, 0x66, 0xf9, 0x22, 0xc3,
    0x01, 0xe3, 0x75, 0x99, 0x20, 0x1c, 0x72, 0xff, 0x93, 0x21, 0x9d, 0xcb, 0xf7, 0x95, 0x6c, 0x4c,
    0x72, 0x02, 0x47, 0xcc, 0x1e, 0xe4, 0xb2, 0x32, 0xaf, 0x9f, 0x6b, 0xfc, 0x2d, 0xe0, 0x94, 0xf9,
    0xfd, 0x5b, 0x53, 0x92, 0x52, 0xb2, 0x34, 0x4e, 0xc2, 0x08, 0xf6, 0x32, 0xbb, 0x52, 0x49, 0x95,
    0x9b, 0xeb, 0x6b, 0xab, 0xcd, 0xd5, 0x8c, 0x94, 0x9a, 0x67, 0x6e, 0xb8, 0xaf, 0xf1, 0x1c, 0xc6,
    0x8b, 0x95, 0x71, 0xe2, 0x0e, 0x8b, 0x1d, 0xc0, 0x0b, 0x80, 0x5f, 0x67, 0x46, 0xb5, 0x09, 0x83,
    0x58, 0x4c, 0xf7, 0xf3, 0x0d, 0x82, 0x31, 0x4c, 0x9c, 0x99, 0x0d, 0x43, 0x36, 0x6c, 0xa2, 0xab,
    0x2f, 0x01, 0x43, 0x5e, 0x19, 0x2f, 0x21, 0xb0, 0x11, 0xf1, 0x38, 0xd5, 0x45, 0xfa, 0x3f, 0x71,
    0x84, 0x9e, 0x76, 0x77, 0xbc, 0x05, 0xe8, 0x82, 0x62, 0xe4, 0x1d, 0x5b, 0xe9, 0x7b, 0xbb, 0x6f,
    0x60, 0xe4, 0xce, 0x87, 0x67, 0x5e, 0xfe, 0x7b, 0xd0, 0xbe, 0xbe, 0x62, 0x97, 0xbf, 0xf6, 0xfa,
    0x27, 0x00, 0x00, 0xff, 0xff, 0x4f, 0x54, 0x11, 0x85, 0xe9, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ProxyClient is the client API for Proxy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProxyClient interface {
    Stop(ctx context.Context, in *ProxyStopRequest, opts ...grpc.CallOption) (*ProxyReplyOnly, error)
    Disconnect(ctx context.Context, in *ProxyDisconnectRequest, opts ...grpc.CallOption) (*ProxyReplyOnly, error)
    Healthz(ctx context.Context, in *ProxyHealthzRequest, opts ...grpc.CallOption) (*ProxyReplyOnly, error)
}

type proxyClient struct {
    cc grpc.ClientConnInterface
}

func NewProxyClient(cc grpc.ClientConnInterface) ProxyClient {
    return &proxyClient{cc}
}

func (c *proxyClient) Stop(ctx context.Context, in *ProxyStopRequest, opts ...grpc.CallOption) (*ProxyReplyOnly, error) {
    out := new(ProxyReplyOnly)
    err := c.cc.Invoke(ctx, "/pb.Proxy/Stop", in, out, opts...)
    if err != nil {
        return nil, err
    }
    return out, nil
}

func (c *proxyClient) Disconnect(ctx context.Context, in *ProxyDisconnectRequest, opts ...grpc.CallOption) (*ProxyReplyOnly, error) {
    out := new(ProxyReplyOnly)
    err := c.cc.Invoke(ctx, "/pb.Proxy/Disconnect", in, out, opts...)
    if err != nil {
        return nil, err
    }
    return out, nil
}

func (c *proxyClient) Healthz(ctx context.Context, in *ProxyHealthzRequest, opts ...grpc.CallOption) (*ProxyReplyOnly, error) {
    out := new(ProxyReplyOnly)
    err := c.cc.Invoke(ctx, "/pb.Proxy/Healthz", in, out, opts...)
    if err != nil {
        return nil, err
    }
    return out, nil
}

// ProxyServer is the server API for Proxy service.
type ProxyServer interface {
    Stop(context.Context, *ProxyStopRequest) (*ProxyReplyOnly, error)
    Disconnect(context.Context, *ProxyDisconnectRequest) (*ProxyReplyOnly, error)
    Healthz(context.Context, *ProxyHealthzRequest) (*ProxyReplyOnly, error)
}

// UnimplementedProxyServer can be embedded to have forward compatible implementations.
type UnimplementedProxyServer struct {
}

func (*UnimplementedProxyServer) Stop(ctx context.Context, req *ProxyStopRequest) (*ProxyReplyOnly, error) {
    return nil, status.Errorf(codes.Unimplemented, "method Stop not implemented")
}
func (*UnimplementedProxyServer) Disconnect(ctx context.Context, req *ProxyDisconnectRequest) (*ProxyReplyOnly, error) {
    return nil, status.Errorf(codes.Unimplemented, "method Disconnect not implemented")
}
func (*UnimplementedProxyServer) Healthz(ctx context.Context, req *ProxyHealthzRequest) (*ProxyReplyOnly, error) {
    return nil, status.Errorf(codes.Unimplemented, "method Healthz not implemented")
}

func RegisterProxyServer(s *grpc.Server, srv ProxyServer) {
    s.RegisterService(&_Proxy_serviceDesc, srv)
}

func _Proxy_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
    in := new(ProxyStopRequest)
    if err := dec(in); err != nil {
        return nil, err
    }
    if interceptor == nil {
        return srv.(ProxyServer).Stop(ctx, in)
    }
    info := &grpc.UnaryServerInfo{
        Server:     srv,
        FullMethod: "/pb.Proxy/Stop",
    }
    handler := func(ctx context.Context, req interface{}) (interface{}, error) {
        return srv.(ProxyServer).Stop(ctx, req.(*ProxyStopRequest))
    }
    return interceptor(ctx, in, info, handler)
}

func _Proxy_Disconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
    in := new(ProxyDisconnectRequest)
    if err := dec(in); err != nil {
        return nil, err
    }
    if interceptor == nil {
        return srv.(ProxyServer).Disconnect(ctx, in)
    }
    info := &grpc.UnaryServerInfo{
        Server:     srv,
        FullMethod: "/pb.Proxy/Disconnect",
    }
    handler := func(ctx context.Context, req interface{}) (interface{}, error) {
        return srv.(ProxyServer).Disconnect(ctx, req.(*ProxyDisconnectRequest))
    }
    return interceptor(ctx, in, info, handler)
}

func _Proxy_Healthz_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
    in := new(ProxyHealthzRequest)
    if err := dec(in); err != nil {
        return nil, err
    }
    if interceptor == nil {
        return srv.(ProxyServer).Healthz(ctx, in)
    }
    info := &grpc.UnaryServerInfo{
        Server:     srv,
        FullMethod: "/pb.Proxy/Healthz",
    }
    handler := func(ctx context.Context, req interface{}) (interface{}, error) {
        return srv.(ProxyServer).Healthz(ctx, req.(*ProxyHealthzRequest))
    }
    return interceptor(ctx, in, info, handler)
}

var _Proxy_serviceDesc = grpc.ServiceDesc{
    ServiceName: "pb.Proxy",
    HandlerType: (*ProxyServer)(nil),
    Methods: []grpc.MethodDesc{
        {
            MethodName: "Stop",
            Handler:    _Proxy_Stop_Handler,
        },
        {
            MethodName: "Disconnect",
            Handler:    _Proxy_Disconnect_Handler,
        },
        {
            MethodName: "Healthz",
            Handler:    _Proxy_Healthz_Handler,
        },
    },
    Streams:  []grpc.StreamDesc{},
    Metadata: "proxy.proto",
}
